### ISSUE TITLE
Strange output values

### ISSUE THREAD

**Issue by PedroCardoso** [jakevdp/pyCRFsuite#3]
I am trying to understand the output array from tagger. The console output seems correct, but if I check the numpy array I have strange results. For the first instance:
[ 8589934592           2  8589934594           3           3  8589934594
           1  4294967298  8589934592 17179869187  8589934592           1
  8589934594 25769803778 12884901888  8589934592  4294967299 12884901888
           4  8589934594  4294967298  8589934592           6 25769803778
           1 25769803778  8589934592  8589934594]

Am I having some kind of strange casting error ?

**Comment by PedroCardoso** [comment]
Using numpy 1.7.1 on python 2.7.5 on macos

**Comment by jakevdp** [comment]
Hi,
I haven't touched this in a long time, and when I left it it was full of bugs.  If you figure out a fix, I'd be happy to accept a PR.

**Comment by tpeng** [comment]
hi @PedroCardoso, not sure if it's related to https://github.com/tpeng/pyCRFsuite/commit/506f7d6efad1055d3d310181fb0733c8bf52398a, maybe you can give it a try.

**Comment by PedroCardoso** [comment]
Hi tpeng. Thanks for the comment. I end up using the default swig wrapper that comes with the lib. Not sure I will get back to this So I wont be able to test.
